CREATE SCHEMA health1
  AUTHORIZATION postgres;

CREATE TABLE health1.renestoffer
( id BIGSERIAL primary key,
  uniquedocid character varying(2048),
  kemisk_navn character varying(2048),
  mst_klas_dsd character varying(2048),
  create_date character varying(40),
  mst_klas_clp character varying(2048),
  klas_stofdirektiv text,
  maerkning_stofdirektiv character varying(2048),
  maerkning_stofdirektiv_lofs character varying(2048),
  lofs_anm character varying(2048),
  lofs_signatur character varying(2048),
  klash_clp text,
  klash_clp_graenser text,
  euhs_aetninger character varying(2048),
  maerkning_clp character varying(2048),
  maerkning_clp_lofs text,
  signalord character varying(2048),
  noter_clp character varying(2048),
  cas_nr character varying(2048),
  cas_nr_bem character varying(2048),
  cas_nr_interne_bem character varying(2048),
  einecs_nr character varying(2048),
  synonymer text,
  index_nr character varying(2048),
  lofs_nummer character varying(2048),
  beaerkninger text,
  lofs_clp  character varying(2048),
  oral_dyr character varying(2048),
  oral_testtype character varying(2048),
  oral_resultat text,
  oral_testar text,
  oral_kilde character varying(2048),
  oral_kildeA character varying(2048),
  dermal_dyr character varying(2048),
  dermal_testtype character varying(2048),
  dermal_resultat text,
  dermal_testar text,
  dermal_kilde character varying(2048),
  dermal_kildeA character varying(2048),
  inhalation_dyr character varying(2048),
  inhalation_eksponeringstid character varying(2048),
  inhalation_tilstandsform character varying(2048),
  inhalation_testtype character varying(2048),
  inhalation_resultat text,
  inhalation_testar text,
  inhalation_kilde character varying(2048),
  inhalation_kildeA character varying(2048),
  hudirritation_dyr character varying(2048),
  hudirritation_dosis character varying(2048),
  hudirritation_varighed character varying(2048),
  hudirritation_resultat text,
  hudirritation_testar text,
  hudirritation_kilde character varying(2048),
  hudirritation_kildeA character varying(2048),
  ojenirritation_dyr character varying(2048),
  ojenirritation_dosis character varying(2048),
  ojenirritation_varighed character varying(2048),
  ojenirritation_resultat text,
  ojenirritation_testar text,
  ojenirritation_kilde character varying(2048),
  ojenirritation_kildeA character varying(2048),
  luftvejsirritation_dyr character varying(2048),
  luftvejsirritation_dosis character varying(2048),
  luftvejsirritation_varighed character varying(2048),
  luftvejsirritation_resultat text,
  luftvejsirritation_testar text,
  luftvejsirritation_kilde character varying(2048),
  luftvejsirritationkildeA character varying(2048),
  overfolsomhed_dyr character varying(2048),
  overfolsomhed_dosis character varying(2048),
  overfolsomhed_varighed character varying(2048),
  overfolsomhed_resultat text,
  overfolsomhed_testar text,
  overfolsomhed_kilde character varying(2048),
  overfolsomhed_kildeA character varying(2048),
  enkelt_ekspodyr character varying(2048),
  enkelt_ekspodosis character varying(2048),
  enkelt_ekspovarighed character varying(2048),
  enkelt_eksporesultat text,
  enkelt_ekspotestar text,
  enkelt_ekspokilde character varying(2048),
  enkelt_ekspokildeA character varying(2048),
  gentagen_ekspodyr character varying(2048),
  gentagen_ekspodosis character varying(2048),
  gentagen_ekspovarighed character varying(2048),
  gentagen_eksporesultat text,
  gentagen_ekspotestar text,
  gentagen_ekspokilde character varying(2048),
  gentagen_ekspokildeA character varying(2048),
  kraefteffekt_resultat text,
  kraefteffekt_kilde character varying(2048),
  kraefteffekt_kildeA character varying(2048),
  mutageneffekt_resultat text,
  mutageneffekt_kilde character varying(2048),
  mutageneffekt_kildeA character varying(2048),
  repeffekt_resultat text,
  repeffekt_kilde character varying(2048),
  repeffekt_kildeA character varying(2048),
  andre_test text, 
  bemaerkninger text,
  miljorxegenvur text,
  n_Klas character varying(2048),
  akut_fisk_artsnavn character varying(2048),
  akut_fisk_testmetode character varying(2048),
  akut_fisk_resultat text,
  akut_fisk_testar text,
  akut_fisk_kilde character varying(2048),
  akut_krebsdyr_artsnavn character varying(2048),
  akut_krebsdyr_testmetode character varying(2048),
  akut_krebsdyr_resultat text,
  akut_krebsdyr_testar text,
  akut_krebsdyr_kilde character varying(2048),
  akut_alge_artsnavn character varying(2048),
  akut_alge_testmetode character varying(2048),
  akut_alge_resultat text,
  akut_alge_testar text,
  akut_alge_kilde character varying(2048),
  kronisk_fisk_artsnavn character varying(2048),
  kronisk_fisk_testmetode character varying(2048),
  kronisk_fisk_resultat text,
  kronisk_fisk_testar text,
  kronisk_fisk_enhed character varying(2048),
  kronisk_krebsdyr_artsnavn character varying(2048),
  kronisk_krebsdyr_testmetode character varying(2048),
  kronisk_krebsdyr_resultat text,
  kronisk_krebsdyr_testar text,
  kronisk_krebsdyr_enhed character varying(2048),
  kronisk_alge_artsnavn character varying(2048),
  kronisk_alge_testmetode character varying(2048),
  kronisk_alge_resultat text,
  kronisk_alge_testar text,
  bio_oct_logpow character varying(2048),
  bio_oct_logkow  character varying(2048),
  bio_oct_testar character varying(2048),
  bcf_dyr character varying(2048),
  bcf_vaerdi character varying(2048),
  bcf_testar character varying(2048),
  let_bionedbrydelig character varying(2048),
  ikke_let_bionedbrydelig character varying(2048),
  bionedbrydelighed_testar  character varying(2048),
  miljo_mobilitet character varying(2048),
  miljo_mobilitet_testar character varying(2048),
  miljo_andre character varying(2048),
  miljo_andre_testar character varying(2048),
  miljo_kildeA character varying(2048),
  miljo_bemaerkninger text,
  damptryk_vaerdi character varying(2048),
  damptryk_enhed character varying(2048),
  damptryk_temp character varying(2048),
  beregnet_damptryk_vaerdi character varying(2048),
  beregnet_damptryk_enhed character varying(2048),
  beregnet_damptryk_temp character varying(2048),
  fordampning_massefylde character varying(2048),
  flammepunkt character varying(2048),
  pka character varying(2048),
  ph character varying(2048),
  kogepunkt character varying(2048),
  udseende character varying(2048),
  smeltepunkt character varying(2048),
  henrys_konstant character varying(2048),
  oploselighed_ivand character varying(2048),
  oploselighed character varying(2048),
  viskositet character varying(2048),
  molekylevaegt character varying(2048),
  molekyleformel character varying(2048),
  eksplosive_egenskaber character varying(2048),
  lugt character varying(2048),
  mal_faktor text,
  mal_faktor_graenser text,
  organisk_forbindelse boolean,
  fysisk_kemiske_kilder character varying(2048),
  fysisk_kemiske_bemaerkning text,
  at_sri character varying(2048),
  at_gv_mgm3 character varying(2048),
  at_gv_ppm character varying(2048),
  diverse character varying(2048),
  kodenummer character varying(2048),
  -- as per doc all fields start with fl_kildexxxx but some of(maked as --) below fields are already convered above
  -- fl_kildeoralrotte character varying(2048),
  -- fl_kildeoralrottea character varying(2048),
  -- fl_kildedermalrotte character varying(2048),
  -- fl_kildedermalrottea character varying(2048),
  -- fl_kildeinhalrotte character varying(2048),
  -- fl_kildeinhalrottea character varying(2048),
  -- fl_kildeojen character varying(2048),
  -- fl_kildeojena character varying(2048),
  -- fl_kildeluft character varying(2048),
  -- fl_kildelufta character varying(2048),
  -- fl_kildesen character varying(2048),
  -- fl_kildesena character varying(2048),
  fl_kildeandret character varying(2048),
  fl_kildeandreta character varying(2048),
  fl_kildeirreversible character varying(2048),
  fl_kildeirreversiblea character varying(2048),
  fl_kildekraft character varying(2048),
  fl_kildekrafta character varying(2048),
  --fl_kildemutagen character varying(2048),
  --fl_kildemutagena character varying(2048),
  --fl_kilderep character varying(2048),
  --fl_kilderepa character varying(2048),
  fl_kildeegenvur character varying(2048),
  --fl_kildefisk character varying(2048),
  fl_kildefiska character varying(2048),
  --fl_kildekrebsdyr character varying(2048),
  fl_kildekrebsdyra character varying(2048),
  --fl_kildealger character varying(2048),
  fl_kildealgera character varying(2048),
  fl_kildeingendatafundet character varying(2048),
  fl_kildefiskkronisk character varying(2048),
  fl_kildefiskakronisk character varying(2048),
  fl_kildekrebsdyrkronisk character varying(2048),
  fl_kildekrebsdyrakronisk character varying(2048),
  fl_kildealgerkronisk character varying(2048),
  fl_kildealgerakronisk character varying(2048),
  fl_kildeingendatafundetkronisk character varying(2048),
  fl_kildelogp character varying(2048),
  fl_kildelogpa character varying(2048),
  fl_kildebcf character varying(2048),
  fl_kildebcfa character varying(2048),
  fl_kildebcionedbrydelig character varying(2048),
  fl_kildebcionedbrydeliga character varying(2048),
  fl_kildemiljomob character varying(2048),
  fl_kildemiljomobandr character varying(2048),
  --fl_kildemiljoandre character varying(2048),
  fl_kildemiljoandr character varying(2048),
  --fl_kildefyskem character varying(2048),
  fl_kildemiljo character varying(2048),
  fl_kildemiljorx character varying(2048),
  fl_kildedampt character varying(2048),
  fl_kildepow character varying(2048),
  fl_kildemassef character varying(2048),
  fl_kildeoplos character varying(2048),
  fl_kildefp character varying(2048),
  fl_kildekp character varying(2048),
  fl_kildeph character varying(2048),
  fl_kildevisko character varying(2048),
  fl_kildemolekyle character varying(2048),
  fl_kildedafnier character varying(2048),
  fl_kildebod5 character varying(2048),
  fl_kildecod character varying(2048),
  fl_kildephotolyse character varying(2048),
  fl_kildehydrolyse character varying(2048),
  fl_kildeandetbio character varying(2048),
  fl_kildeokoart character varying(2048),
  fl_kildeokoart1 character varying(2048),
  fl_kildeozon character varying(2048),
  fl_kildehud character varying(2048),
  fl_kildehuda character varying(2048)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE health1.renestoffer
  OWNER TO postgres;


-- Function: health1.data_fill()

-- DROP FUNCTION health1.data_fill();

CREATE OR REPLACE FUNCTION health1.data_fill()
  RETURNS integer AS
$BODY$DECLARE 
rec record;

BEGIN
FOR rec IN select * from health.stoffer
LOOP

INSERT INTO health1.renestoffer(uniquedocid, kemisk_navn, mst_klas_dsd, create_date, klas_stofdirektiv, maerkning_stofdirektiv_lofs, lofs_anm, lofs_signatur,klash_clp, klash_clp_graenser, euhs_aetninger, maerkning_clp_lofs, noter_clp, cas_nr_bem, cas_nr_interne_bem, einecs_nr, synonymer, index_nr, lofs_nummer, lofs_clp,  oral_dyr, oral_testtype, oral_resultat, oral_testar, oral_kilde, oral_kildeA, dermal_dyr, dermal_testtype, dermal_resultat, dermal_testar, dermal_kilde, dermal_kildeA, inhalation_dyr, inhalation_eksponeringstid, inhalation_tilstandsform, inhalation_testtype, inhalation_resultat, inhalation_testar, inhalation_kilde, inhalation_kildeA, hudirritation_dyr, hudirritation_dosis, hudirritation_varighed, hudirritation_resultat, hudirritation_testar, hudirritation_kilde, hudirritation_kildeA, ojenirritation_dyr, ojenirritation_dosis, ojenirritation_varighed, ojenirritation_resultat, ojenirritation_kilde, ojenirritation_kildeA, luftvejsirritation_dyr, luftvejsirritation_dosis, luftvejsirritation_varighed, luftvejsirritation_resultat, luftvejsirritation_testar, luftvejsirritation_kilde, luftvejsirritationkildeA, overfolsomhed_dyr, overfolsomhed_dosis, overfolsomhed_varighed, overfolsomhed_resultat, overfolsomhed_testar, overfolsomhed_kilde, overfolsomhed_kildeA, kraefteffekt_resultat, kraefteffekt_kilde, kraefteffekt_kildeA, mutageneffekt_resultat, mutageneffekt_kilde, mutageneffekt_kildeA, repeffekt_resultat, repeffekt_kilde, repeffekt_kildeA, andre_test, miljorxegenvur,n_Klas, akut_fisk_artsnavn, akut_fisk_testmetode, akut_fisk_resultat, akut_fisk_testar, akut_fisk_kilde, akut_krebsdyr_artsnavn, akut_krebsdyr_testmetode, akut_krebsdyr_resultat, akut_krebsdyr_testar, akut_krebsdyr_kilde, akut_alge_artsnavn, akut_alge_testmetode, akut_alge_resultat, akut_alge_testar, akut_alge_kilde, kronisk_fisk_artsnavn, kronisk_fisk_testmetode, kronisk_fisk_resultat, kronisk_fisk_testar,  kronisk_krebsdyr_artsnavn, kronisk_krebsdyr_testmetode, kronisk_krebsdyr_resultat, kronisk_krebsdyr_testar, kronisk_alge_artsnavn, kronisk_alge_testmetode, kronisk_alge_resultat, kronisk_alge_testar, bio_oct_logpow, bio_oct_logkow, bcf_vaerdi, bcf_testar, let_bionedbrydelig, ikke_let_bionedbrydelig, bionedbrydelighed_testar, miljo_mobilitet, miljo_mobilitet_testar, miljo_andre, miljo_andre_testar, miljo_kildeA, damptryk_vaerdi, damptryk_enhed, damptryk_temp, beregnet_damptryk_vaerdi, beregnet_damptryk_temp, flammepunkt, pka, ph, kogepunkt, udseende, smeltepunkt, henrys_konstant, oploselighed_ivand, oploselighed, viskositet, molekylevaegt, molekyleformel, eksplosive_egenskaber, lugt, fysisk_kemiske_kilder, at_sri, at_gv_mgm3, at_gv_ppm, diverse,fl_kildeandret ,fl_kildeandreta, fl_kildeirreversible, fl_kildeirreversiblea, fl_kildekraft, fl_kildekrafta, fl_kildeegenvur, fl_kildefiska, fl_kildekrebsdyra, fl_kildealgera, fl_kildeingendatafundet, fl_kildefiskkronisk, fl_kildefiskakronisk, fl_kildekrebsdyrkronisk, fl_kildekrebsdyrakronisk, fl_kildealgerkronisk, fl_kildealgerakronisk, fl_kildeingendatafundetkronisk, fl_kildelogp, fl_kildelogpa, fl_kildebcf, fl_kildebcfa, fl_kildebcionedbrydelig, fl_kildebcionedbrydeliga, fl_kildemiljomob, fl_kildemiljomobandr, fl_kildemiljoandr, fl_kildemiljo, fl_kildemiljorx, fl_kildedampt, fl_kildepow, fl_kildemassef, fl_kildeoplos, fl_kildefp, fl_kildekp, fl_kildeph,  fl_kildevisko, fl_kildemolekyle, fl_kildedafnier, fl_kildebod5, fl_kildecod, fl_kildephotolyse, fl_kildehydrolyse, fl_kildeandetbio, fl_kildeokoart, fl_kildeokoart1, fl_kildeozon, fl_kildehud, fl_kildehuda, mal_faktor, mal_faktor_graenser ) values (rec.fl_uniquedocid, rec.fl_kemisknavn, rec.fl_mstklas, now()::timestamp(0), (case when rec.fl_klasr01 is null then '' else rec.fl_klasr01 end) || '||' || (case when rec.fl_klasr02 is null then '' else rec.fl_klasr02 end) || '||' || (case when rec.fl_klasr03 is null then '' else rec.fl_klasr03 end) || '||' || (case when rec.fl_klasr04 is null then '' else rec.fl_klasr04 end) || '||' || (case when rec.fl_klasr05 is null then '' else rec.fl_klasr05 end) || '||' || (case when rec.fl_klasr06 is null then '' else rec.fl_klasr06 end) || '||' || (case when rec.fl_klasr07 is null then '' else rec.fl_klasr07 end) || '||' || (case when rec.fl_klasr08 is null then '' else rec.fl_klasr08 end) || '||' || (case when rec.fl_klasr09 is null then '' else rec.fl_klasr09 end) || '||' || (case when rec.fl_klasr10 is null then '' else rec.fl_klasr10 end) || '||' || (case when rec.fl_klasr011 is null then '' else rec.fl_klasr011 end) || '||' || (case when rec.fl_klasr012 is null then '' else rec.fl_klasr012 end) || '||' || (case when rec.fl_klasr013 is null then '' else rec.fl_klasr013 end) || '||' || (case when rec.fl_klasr014 is null then '' else rec.fl_klasr014 end) || '||' || (case when rec.fl_klasr015 is null then '' else rec.fl_klasr015 end) || '||' || (case when rec.fl_klasr11 is null then '' else rec.fl_klasr11 end) || '||' || (case when rec.fl_klasr12 is null then '' else rec.fl_klasr12 end) || '||' || (case when rec.fl_klasr13 is null then '' else rec.fl_klasr13 end) || '||' || (case when rec.fl_klasr14 is null then '' else rec.fl_klasr14 end) || '||' || (case when rec.fl_klasr15 is null then '' else rec.fl_klasr15 end), rec.fl_maerkning, rec.fl_lofsanm, rec.fl_lofssignatur, (case when rec.fl_klash01 is null then '' else rec.fl_klash01 end) || '||' || (case when rec.fl_klash02 is null then '' else rec.fl_klash02 end) || '||' || (case when rec.fl_klash03 is null then '' else rec.fl_klash03 end) || '||' || (case when rec.fl_klash04 is null then '' else rec.fl_klash04 end) || '||' || (case when rec.fl_klash05 is null then '' else rec.fl_klash05 end) || '||' || (case when rec.fl_klash06 is null then '' else rec.fl_klash06 end) || '||' || (case when rec.fl_klash07 is null then '' else rec.fl_klash07 end) || '||' || (case when rec.fl_klash08 is null then '' else rec.fl_klash08 end) || '||' || (case when rec.fl_klash09 is null then '' else rec.fl_klash09 end) || '||' || (case when rec.fl_klash010 is null then '' else rec.fl_klash010 end) || '||' || (case when rec.fl_klash011 is null then '' else rec.fl_klash011 end) || '||' || (case when rec.fl_klash012 is null then '' else rec.fl_klash012 end) || '||' || (case when rec.fl_klash013 is null then '' else rec.fl_klash013 end) || '||' || (case when rec.fl_klash014 is null then '' else rec.fl_klash014 end) || '||' || (case when rec.fl_klash015 is null then '' else rec.fl_klash015 end), (case when rec.fl_klaspct01 is null then '' else rec.fl_klaspct01 end) || '||' || (case when rec.fl_klaspct02 is null then '' else rec.fl_klaspct02 end) || '||' || (case when rec.fl_klaspct03 is null then '' else rec.fl_klaspct03 end) || '||' || (case when rec.fl_klaspct04 is null then '' else rec.fl_klaspct04 end) || '||' || (case when rec.fl_klaspct05 is null then '' else rec.fl_klaspct05 end) || '||' || (case when rec.fl_klaspct06 is null then '' else rec.fl_klaspct06 end) || '||' || (case when rec.fl_klaspct07 is null then '' else rec.fl_klaspct07 end) || '||' || (case when rec.fl_klaspct08 is null then '' else rec.fl_klaspct08 end) || '||' || (case when rec.fl_klaspct09 is null then '' else rec.fl_klaspct09 end) || '||' || (case when rec.fl_klaspct010 is null then '' else rec.fl_klaspct010 end) || '||' || (case when rec.fl_klaspct011 is null then '' else rec.fl_klaspct011 end) || '||' || (case when rec.fl_klaspct012 is null then '' else rec.fl_klaspct012 end) || '||' || (case when rec.fl_klaspct013 is null then '' else rec.fl_klaspct013 end) || '||' || (case when rec.fl_klaspct014 is null then '' else rec.fl_klaspct014 end) || '||' || (case when rec.fl_klaspct015 is null then '' else rec.fl_klaspct015 end), rec.fl_euhsaetninger, (case when rec.fl_maerkning_clp is null then '' else rec.fl_maerkning_clp end) || '||' || (case when rec.fl_maerkning_clp_hazard is null then '' else rec.fl_maerkning_clp_hazard end) || '||' || (case when rec.fl_maerkning_clp_picto is null then '' else rec.fl_maerkning_clp_picto end), rec.fl_noter_clp, rec.fl_casnrref, rec.fl_casnrintbem, rec.fl_einecsnr, rec.fl_synonymer, rec.fl_indexnr, rec.fl_lofsnummer, rec.fl_body, rec.fl_dyroral, rec.fl_oraltestt, rec.fl_oralrotte,rec.fl_oraltaar, rec.fl_kildeoralrotte, rec.fl_kildeoralrottea, rec.fl_Dyrdermal, rec.fl_Dermaltestt, rec.fl_Dermalrotte, rec.fl_Dermalaar, rec.fl_Kildedermalrotte, rec.fl_KildedermalrotteA, rec.fl_dyrinhal, rec.fl_inhaltestt, rec.fl_inhaleksrotte, rec.fl_inhaltilstandsform, rec.fl_inhalrotte, rec.fl_inhalaar,rec.fl_kildeinhalrotte,rec.fl_kildeinhalrottea, rec.fl_huddyr, rec.fl_huddosis, rec.fl_hudvarighed, rec.fl_hudresultat, rec.fl_hudaar, rec.fl_kildehud, rec.fl_kildehuda, rec.fl_ojendyr, rec.fl_ojendosis, rec.fl_ojenvarighed, rec.fl_ojenresultat, rec.fl_kildeojen, rec.fl_kildeojena, rec.fl_luftdyr, rec.fl_luftdosis, rec.fl_luftvarighed, rec.fl_luftresultat, rec.fl_luftaar, rec.fl_kildeluft, rec.fl_kildelufta, rec.fl_sendyr, rec.fl_sendosis, rec.fl_varighed, rec.fl_senresultat, rec.fl_senaar, rec.fl_kildesen, rec.fl_kildesena, rec.fl_krafteffekt, rec.fl_kildekraft, rec.fl_kildekrafta, rec.fl_mutageneffekt, rec.fl_kildemutagen, rec.fl_kildemutagena, rec.fl_repeffekt, rec.fl_kilderep, rec.fl_kilderepa, rec.fl_andretest, rec.fl_miljorxegenvur, rec.fl_nclassklas,rec.fl_fisk, rec.fl_fisketest, rec.fl_fiskeresultat, rec.fl_fisktestar, rec.fl_kildefisk, rec.fl_krebsdyr, rec.fl_krebsdyrtest, rec.fl_krebsdyrresultat, rec.fl_krebsdyrtestar, rec.fl_kildekrebsdyr, rec.fl_alge, rec.fl_algetest, rec.fl_algeresultat, rec.fl_algetestar, rec.fl_kildealger, rec.fl_fiskkronisk, rec.fl_fisketestkronisk, rec.fl_fiskresultatkronisk, rec.fl_fisktestarkronisk, rec.fl_krebsdyrkronisk, rec.fl_krebsdyrtestkronisk, rec.fl_krebsdyrresultatkronisk_1, rec.fl_krebsdyrtestarkronisk, rec.fl_algekronisk, rec.fl_algetestkronisk, rec.fl_algeresultatkronisk_1, rec.fl_algetestarkronisk, rec.fl_logpow, rec.fl_logkow, rec.fl_bcfmindreend, rec.fl_bcftestar, rec.fl_bionedbrydelig, rec.fl_bionedbrydelig, rec.fl_bcftestar, rec.fl_miljomob, rec.fl_mobilitettestar, rec.fl_miljoandre, rec.fl_andettestar, rec.fl_kildemiljoandre, rec.fl_damptryk, rec.fl_damptrykenhed, rec.fl_damptemp, rec.fl_bedtryk, rec.fl_bedtemp, rec.fl_flammepunkt, rec.fl_pka, rec.fl_ph, rec.fl_kogepunkt, rec.fl_udseende, rec.fl_smeltepunkt, rec.fl_henryskonstant, rec.fl_oploselighed, rec.fl_oploselighed_1, rec.fl_viskositet, rec.fl_molekylevagt, rec.fl_molekyleformel, rec.fl_eks, rec.fl_lugt, rec.fl_kildefyskem, rec.fl_neurosri, rec.fl_atgvmgm3, rec.fl_atgvppm, rec.fl_anmarkninger, rec.fl_kildeandret ,rec.fl_kildeandreta, rec.fl_kildeirreversible, rec.fl_kildeirreversiblea, rec.fl_kildekraft, rec.fl_kildekrafta, rec.fl_kildeegenvur, rec.fl_kildefiska, rec.fl_kildekrebsdyra, rec.fl_kildealgera, rec.fl_kildeingendatafundet, rec.fl_kildefiskkronisk, rec.fl_kildefiskakronisk, rec.fl_kildekrebsdyrkronisk, rec.fl_kildekrebsdyrakronisk, rec.fl_kildealgerkronisk, rec.fl_kildealgerakronisk, rec.fl_kildeingendatafundetkronisk, rec.fl_kildelogp, rec.fl_kildelogpa, rec.fl_kildebcf, rec.fl_kildebcfa, rec.fl_kildebcionedbrydelig, rec.fl_kildebcionedbrydeliga, rec.fl_kildemiljomob, rec.fl_kildemiljomobandr, rec.fl_kildemiljoandr, rec.fl_kildemiljo, rec.fl_kildemiljorx, rec.fl_kildedampt, rec.fl_kildepow, rec.fl_kildemassef, rec.fl_kildeoplos, rec.fl_kildefp, rec.fl_kildekp, rec.fl_kildeph,  rec.fl_kildevisko, rec.fl_kildemolekyle, rec.fl_kildedafnier, rec.fl_kildebod5, rec.fl_kildecod, rec.fl_kildephotolyse, rec.fl_kildehydrolyse, rec.fl_kildeandetbio, rec.fl_kildeokoart, rec.fl_kildeokoart1, rec.fl_kildeozon, rec.fl_kildehud, rec.fl_kildehuda,(case when rec.fl_mal01 is null then '' else rec.fl_mal01 end) || '||' || (case when rec.fl_mal02 is null then '' else rec.fl_mal02 end) || '||' || (case when rec.fl_mal03 is null then '' else rec.fl_mal03 end), (case when rec.fl_malpct01 is null then '' else rec.fl_malpct01 end) || '||' || (case when rec.fl_malpct02 is null then '' else rec.fl_malpct02 end) || '||' || (case when rec.fl_malpct03 is null then '' else rec.fl_malpct03 end));

END LOOP;
RETURN 1;
END;$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION health1.data_fill()
  OWNER TO postgres;
COMMENT ON FUNCTION health1.data_fill() IS 'This function insert data row by row into renestoffer, milijo_klass and data_sundhed table.';


Select health1.data_fill();

CREATE OR REPLACE FUNCTION health1.searchfun(searchfield character varying) RETURNS json AS
$BODY$declare
searchname character varying(255);
BEGIN 
searchname := searchfun.searchfield;
return(SELECT array_to_json(array_agg(t)) FROM health1.renestoffer t where id::TEXT like '%'||searchname||'%' or uniquedocid like '%'||searchname||'%' or kemisk_navn like '%'||searchname||'%' or mst_klas_dsd like '%'||searchname||'%' or create_date like '%'||searchname||'%' or mst_klas_clp like '%'||searchname||'%' or klas_stofdirektiv like '%'||searchname||'%' or maerkning_stofdirektiv like '%'||searchname||'%' or maerkning_stofdirektiv_lofs like '%'||searchname||'%' or lofs_anm like '%'||searchname||'%' or lofs_signatur like '%'||searchname||'%' or klash_clp like '%'||searchname||'%' or klash_clp_graenser like '%'||searchname||'%' or euhs_aetninger like '%'||searchname||'%'
  or maerkning_clp like '%'||searchname||'%' or maerkning_clp_lofs like '%'||searchname||'%' or signalord like '%'||searchname||'%' or noter_clp like '%'||searchname||'%' or cas_nr like '%'||searchname||'%' or cas_nr_bem like '%'||searchname||'%' or cas_nr_interne_bem like '%'||searchname||'%' or einecs_nr like '%'||searchname||'%' or synonymer like '%'||searchname||'%' or index_nr like '%'||searchname||'%' or lofs_nummer like '%'||searchname||'%' or beaerkninger like '%'||searchname||'%' or lofs_clp like '%'||searchname||'%' or oral_dyr like '%'||searchname||'%' or oral_testtype like '%'||searchname||'%' or oral_resultat like '%'||searchname||'%' or oral_testar like '%'||searchname||'%' or oral_kilde like '%'||searchname||'%' or oral_kildea like '%'||searchname||'%' or dermal_dyr like '%'||searchname||'%' or dermal_testtype like '%'||searchname||'%' or dermal_resultat like '%'||searchname||'%' or dermal_testar like '%'||searchname||'%' or dermal_kilde like '%'||searchname||'%' or dermal_kildea like '%'||searchname||'%' or inhalation_dyr like '%'||searchname||'%' or inhalation_eksponeringstid like '%'||searchname||'%' or inhalation_tilstandsform like '%'||searchname||'%' or inhalation_testtype like '%'||searchname||'%' or inhalation_resultat like '%'||searchname||'%' or inhalation_testar like '%'||searchname||'%' or inhalation_kilde like '%'||searchname||'%' or inhalation_kildea like '%'||searchname||'%' or hudirritation_dyr like '%'||searchname||'%' or hudirritation_dosis like '%'||searchname||'%' or hudirritation_varighed like '%'||searchname||'%' or hudirritation_resultat like '%'||searchname||'%' or hudirritation_testar like '%'||searchname||'%' or hudirritation_kilde like '%'||searchname||'%' or hudirritation_kildea like '%'||searchname||'%' or ojenirritation_dyr like '%'||searchname||'%' or ojenirritation_dosis like '%'||searchname||'%' or ojenirritation_varighed like '%'||searchname||'%' or ojenirritation_resultat like '%'||searchname||'%' or ojenirritation_testar like '%'||searchname||'%' or ojenirritation_kilde like '%'||searchname||'%' or ojenirritation_kildea like '%'||searchname||'%' or luftvejsirritation_dyr like '%'||searchname||'%' or luftvejsirritation_dosis like '%'||searchname||'%' or luftvejsirritation_varighed like '%'||searchname||'%' or luftvejsirritation_resultat like '%'||searchname||'%' or luftvejsirritation_testar like '%'||searchname||'%' or luftvejsirritation_kilde like '%'||searchname||'%' or luftvejsirritationkildea like '%'||searchname||'%' or overfolsomhed_dyr like '%'||searchname||'%' or overfolsomhed_dosis like '%'||searchname||'%' or overfolsomhed_varighed like '%'||searchname||'%' or overfolsomhed_resultat like '%'||searchname||'%' or overfolsomhed_testar like '%'||searchname||'%' or overfolsomhed_kilde like '%'||searchname||'%' or overfolsomhed_kildea like '%'||searchname||'%' or enkelt_ekspodyr like '%'||searchname||'%' or enkelt_ekspodosis like '%'||searchname||'%' or enkelt_ekspovarighed like '%'||searchname||'%' or enkelt_eksporesultat like '%'||searchname||'%' or enkelt_ekspotestar like '%'||searchname||'%' or enkelt_ekspokilde like '%'||searchname||'%' or enkelt_ekspokildea like '%'||searchname||'%' or gentagen_ekspodyr like '%'||searchname||'%' or gentagen_ekspodosis like '%'||searchname||'%' or gentagen_ekspovarighed like '%'||searchname||'%' or gentagen_eksporesultat like '%'||searchname||'%' or gentagen_ekspotestar like '%'||searchname||'%' or gentagen_ekspokilde like '%'||searchname||'%' or gentagen_ekspokildea like '%'||searchname||'%' or kraefteffekt_resultat like '%'||searchname||'%' or kraefteffekt_kilde like '%'||searchname||'%' or kraefteffekt_kildea like '%'||searchname||'%' or mutageneffekt_resultat like '%'||searchname||'%' or mutageneffekt_kilde like '%'||searchname||'%' or mutageneffekt_kildea like '%'||searchname||'%' or repeffekt_resultat like '%'||searchname||'%' or repeffekt_kilde like '%'||searchname||'%' or repeffekt_kildea like '%'||searchname||'%' or andre_test like '%'||searchname||'%' or bemaerkninger like '%'||searchname||'%' or miljorxegenvur like '%'||searchname||'%' or n_klas like '%'||searchname||'%' or akut_fisk_artsnavn like '%'||searchname||'%' or akut_fisk_testmetode like '%'||searchname||'%' or akut_fisk_resultat like '%'||searchname||'%' or akut_fisk_testar like '%'||searchname||'%' or akut_fisk_kilde like '%'||searchname||'%' or akut_krebsdyr_artsnavn like '%'||searchname||'%' or akut_krebsdyr_testmetode like '%'||searchname||'%' or akut_krebsdyr_resultat like '%'||searchname||'%' or akut_krebsdyr_testar like '%'||searchname||'%' or akut_krebsdyr_kilde like '%'||searchname||'%' or akut_alge_artsnavn like '%'||searchname||'%' or akut_alge_testmetode like '%'||searchname||'%' or akut_alge_resultat like '%'||searchname||'%' or akut_alge_testar like '%'||searchname||'%' or akut_alge_kilde like '%'||searchname||'%' or kronisk_fisk_artsnavn like '%'||searchname||'%' or kronisk_fisk_testmetode like '%'||searchname||'%' or kronisk_fisk_resultat like '%'||searchname||'%' or kronisk_fisk_testar like '%'||searchname||'%' or kronisk_fisk_enhed like '%'||searchname||'%' or kronisk_krebsdyr_artsnavn like '%'||searchname||'%' or kronisk_krebsdyr_testmetode like '%'||searchname||'%' or kronisk_krebsdyr_resultat like '%'||searchname||'%' or kronisk_krebsdyr_testar like '%'||searchname||'%' or kronisk_krebsdyr_enhed like '%'||searchname||'%' or kronisk_alge_artsnavn like '%'||searchname||'%' or kronisk_alge_testmetode like '%'||searchname||'%' or kronisk_alge_resultat like '%'||searchname||'%' or kronisk_alge_testar like '%'||searchname||'%' or bio_oct_logpow like '%'||searchname||'%' or bio_oct_logkow like '%'||searchname||'%' or bio_oct_testar like '%'||searchname||'%' or bcf_dyr like '%'||searchname||'%' or bcf_vaerdi like '%'||searchname||'%' or bcf_testar like '%'||searchname||'%' or let_bionedbrydelig like '%'||searchname||'%' or ikke_let_bionedbrydelig like '%'||searchname||'%' or bionedbrydelighed_testar like '%'||searchname||'%' or miljo_mobilitet like '%'||searchname||'%' or miljo_mobilitet_testar like '%'||searchname||'%' or miljo_andre like '%'||searchname||'%' or miljo_andre_testar like '%'||searchname||'%' or miljo_kildea like '%'||searchname||'%' or miljo_bemaerkninger like '%'||searchname||'%' or damptryk_vaerdi like '%'||searchname||'%' or damptryk_enhed like '%'||searchname||'%' or damptryk_temp like '%'||searchname||'%' or beregnet_damptryk_vaerdi like '%'||searchname||'%' or beregnet_damptryk_enhed like '%'||searchname||'%' or beregnet_damptryk_temp like '%'||searchname||'%' or fordampning_massefylde like '%'||searchname||'%' or flammepunkt like '%'||searchname||'%' or pka like '%'||searchname||'%' or ph like '%'||searchname||'%' or kogepunkt like '%'||searchname||'%' or udseende like '%'||searchname||'%' or smeltepunkt like '%'||searchname||'%' or henrys_konstant like '%'||searchname||'%' or oploselighed_ivand like '%'||searchname||'%' or oploselighed like '%'||searchname||'%' or viskositet like '%'||searchname||'%' or molekylevaegt like '%'||searchname||'%' or molekyleformel like '%'||searchname||'%' or eksplosive_egenskaber like '%'||searchname||'%' or lugt like '%'||searchname||'%' or mal_faktor like '%'||searchname||'%' or mal_faktor_graenser like '%'||searchname||'%' or fysisk_kemiske_kilder like '%'||searchname||'%' or fysisk_kemiske_bemaerkning like '%'||searchname||'%' or at_sri like '%'||searchname||'%' or at_gv_mgm3 like '%'||searchname||'%' or at_gv_ppm like '%'||searchname||'%' or diverse like '%'||searchname||'%' or kodenummer like '%'||searchname||'%' or fl_kildeandret like '%'||searchname||'%' or fl_kildeandreta like '%'||searchname||'%' or fl_kildeirreversible like '%'||searchname||'%' or fl_kildeirreversiblea like '%'||searchname||'%' or fl_kildekraft like '%'||searchname||'%' or fl_kildekrafta like '%'||searchname||'%' or fl_kildeegenvur like '%'||searchname||'%' or fl_kildefiska like '%'||searchname||'%' or fl_kildekrebsdyra like '%'||searchname||'%' or fl_kildealgera like '%'||searchname||'%' or fl_kildeingendatafundet like '%'||searchname||'%' or fl_kildefiskkronisk like '%'||searchname||'%' or fl_kildefiskakronisk like '%'||searchname||'%' or fl_kildekrebsdyrkronisk like '%'||searchname||'%' or fl_kildekrebsdyrakronisk like '%'||searchname||'%' or fl_kildealgerkronisk like '%'||searchname||'%' or fl_kildealgerakronisk like '%'||searchname||'%' or fl_kildeingendatafundetkronisk like '%'||searchname||'%' or fl_kildelogp like '%'||searchname||'%' or fl_kildelogpa like '%'||searchname||'%' or fl_kildebcf like '%'||searchname||'%' or fl_kildebcfa like '%'||searchname||'%' or fl_kildebcionedbrydelig like '%'||searchname||'%' or fl_kildebcionedbrydeliga like '%'||searchname||'%' or fl_kildemiljomob like '%'||searchname||'%' or fl_kildemiljomobandr like '%'||searchname||'%' or fl_kildemiljoandr like '%'||searchname||'%' or fl_kildemiljo like '%'||searchname||'%' or fl_kildemiljorx like '%'||searchname||'%' or fl_kildedampt like '%'||searchname||'%' or fl_kildepow like '%'||searchname||'%' or fl_kildemassef like '%'||searchname||'%' or fl_kildeoplos like '%'||searchname||'%' or fl_kildefp like '%'||searchname||'%'
  or fl_kildekp like '%'||searchname||'%' or fl_kildeph like '%'||searchname||'%' or fl_kildevisko like '%'||searchname||'%' or fl_kildemolekyle like '%'||searchname||'%' or fl_kildedafnier like '%'||searchname||'%' or fl_kildebod5 like '%'||searchname||'%' or fl_kildecod like '%'||searchname||'%' or fl_kildephotolyse like '%'||searchname||'%' or fl_kildehydrolyse like '%'||searchname||'%' or fl_kildeandetbio like '%'||searchname||'%' or fl_kildeokoart like '%'||searchname||'%' or fl_kildeokoart1 like '%'||searchname||'%' or fl_kildeozon like '%'||searchname||'%'
   or fl_kildehud like '%'||searchname||'%' or fl_kildehud like '%'||searchname||'%');
end;

$BODY$
LANGUAGE plpgsql VOLATILE NOT LEAKPROOF
COST 100;

commit;

